## 边缘检测Canny

In [2]:
import cv2
import numpy as np

img = cv2.imread('./lena.jpg')

# 阈值给的稍大，绘制的边缘不够精细
lena1 = cv2.Canny(img, 100, 200)

# 可以通过给小一点的阈值，等到较为精细的边缘
lena2 = cv2.Canny(img, 64, 128)

cv2.imshow('lena', np.hstack((lena1, lena2)))

cv2.waitKey(0)
cv2.destroyAllWindows()

## 形态学

### 全局二值化

In [15]:
import cv2
import numpy as np

img = cv2.imread('./dog.jpg')

# 二值化操作是对灰度图像操作，把dog变成灰度图像
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# threshold返回两个值，一个是阈值，一个是处理后的图片
thresh, dst = cv2.threshold(gray, 120, 255, cv2.THRESH_BINARY)

print(thresh)
cv2.imshow('dst', np.hstack((gray, dst)))

cv2.waitKey(0)
cv2.destroyAllWindows()

120.0


### 自适应阈值二值化

In [5]:
# 因为光线问题，全局二值化会导致有部分地方看不见了，这时候就需要自适应阈值二值化了
import cv2
import numpy as np

img = cv2.imread('./dog.jpg')

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# 自适应阈值二值化只有一个返回值
dst = cv2.adaptiveThreshold(gray, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 15, 0)

cv2.imshow('dst', np.hstack((gray, dst)))

cv2.waitKey(0)
cv2.destroyAllWindows()

### 腐蚀操作

In [8]:
import cv2
import numpy as np

img = cv2.imread('./test.jpg')

# 定义核
kernel = np.ones((3, 3), np.uint8)

# 自适应阈值二值化只有一个返回值
dst = cv2.erode(img, kernel, iterations=1)

cv2.imshow('dst', np.hstack((img, dst)))

cv2.waitKey(0)
cv2.destroyAllWindows()

### 获取形态学卷积核

In [13]:
import cv2
import numpy as np

img = cv2.imread('./black.jpg')

# 椭圆
kernel1 = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (9, 9))
print(kernel1)

print('--------------------------------')

# 十字架
kernel2 = cv2.getStructuringElement(cv2.MORPH_CROSS, (5, 5))
print(kernel2)

# 腐蚀
dst = cv2.erode(img, kernel)
cv2.imshow('dst', dst)

cv2.waitKey(0)
cv2.destroyAllWindows()

[[0 0 0 0 1 0 0 0 0]
 [0 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 0]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [0 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 0]
 [0 0 0 0 1 0 0 0 0]]
--------------------------------
[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]
